[modules.icmp]
		longname="ICMP Monitor"

[hosts.git-keldu]
address="git.keldu.de"
[[hosts.git-keldu.modules]]
name="icmp"

[hosts.www-fsmi]
address="www.fsmi.uni-karlsruhe.de"
[[hosts.www-fsmi.modules]]
name="icmp"