[[module]]
	name="icmp"
	longname="ICMP Monitor"

[[host]]
	name="git-keldu"
	address="git.keldu.de"
	[[Host.Modules]]
		name="icmp"
[[host]]
	name="www-fsmi"
	address="www.fsmi.uni-karlsruhe.de"
	[[host.modules]]
		name="icmp"